## TENSORFLOW TUTORIAL

In [22]:
import math
import numpy as np
import h5py
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.python.framework import ops
from tf_utils import load_dataset, random_mini_batches, convert_to_one_hot, predict

%matplotlib inline
np.random.seed(1)

In [23]:
a = tf.constant(10)
b = tf.constant(8)
sq_diff = tf.Variable((a-b)**2)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(sq_diff))

4


In [24]:
a = tf.constant(2)
b = tf.constant(5)
c = a*b
print(c)

Tensor("mul_4:0", shape=(), dtype=int32)


In [26]:
sess = tf.Session()
sess.run(c)

10

In [28]:
val = np.array([2,3,4,5])
x = tf.placeholder(tf.int64)
sess.run(2*x, feed_dict = {x:val})

array([ 4,  6,  8, 10], dtype=int64)

In [41]:
def linear_function():
    x = tf.constant(np.random.randn(3,1))
    w = tf.constant(np.random.randn(4,3))
    b = tf.constant(np.random.randn(4,1))
    y = tf.matmul(w,x)+b
    
    sess = tf.Session()
    result = sess.run(y)
    sess.close()
    return result
linear_function()

array([[ 3.20852897],
       [-0.3290987 ],
       [-0.49011445],
       [-2.47594373]])

In [49]:
def sigmoid(z):
    x = tf.placeholder(tf.float32)
    sigmoid = tf.sigmoid(x)
    
    sess = tf.Session()
    result = sess.run(sigmoid,feed_dict = {x:z})
    sess.close()
    return result
sigmoid(0.8)

0.6899745

In [51]:
def cost(logit,label):
    z = tf.placeholder(tf.float32)
    y = tf.placeholder(tf.float32)
    cost = tf.nn.sigmoid_cross_entropy_with_logits(logits = z,labels = y)
    
    sess = tf.Session()
    result = sess.run(cost, feed_dict = {z:logit, y:label})
    sess.close()
    
    return result
logits = sigmoid(np.array([0.2,0.4,0.7,0.9]))
cost = cost(logits, np.array([0,0,1,1]))
print ("cost = " + str(cost))

cost = [1.0053872  1.0366409  0.4138543  0.39956614]


In [60]:
#tf.one_hot(labels,depth,axis)
def one_hot_matrix(labels,c):
    c = tf.constant(c)
    one_hot_matrix = tf.one_hot(labels,c,axis = 1 )
    
    sess = tf.Session()
    result = sess.run(one_hot_matrix )
    sess.close() 
    
    return result
labels = np.array([1,20,3,0,2,1])
one_hot = one_hot_matrix(labels, c = 4)
print ("one_hot = " + str(one_hot))

one_hot = [[0. 1. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]
